{application,websocket_client,
             [{description,"Erlang websocket client"},
              {vsn,"1.5.0"},
              {registered,[]},
              {applications,[kernel,stdlib,ssl,crypto,inets]},
              {env,[]},
              {modules,[websocket_client,websocket_req,wsc_lib]},
              {links,[{"Github",
                       "https://github.com/sanmiguel/websocket_client"}]},
              {licenses,["MIT"]}]}.
